name: example-workflow
on:
    push:
        branches:
            - main
jobs:
  hello-world:
    if: github.repository == 'devanshumevada/Github-Examples'
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World"
        run:  echo "Hello World!"
  goodbye-moon:
    runs-on: ubuntu-latest
    steps:
      - name: "Goodbye Moon"
        run:  echo "Goodbye Moon!"